name: CVBlocks
main: org.cubeville.cvblocks.CVBlocks
author: [FrediW, Ptown16]
version: '1.20'
api-version: '1.20'
depend: [CVTools, WorldEdit, WorldGuard]

commands:
  cvblocks:
    description: CVBlocks command
    permission: cvblocks.admin

permissions:

  cvblocks.admin:
    description: General access to all cvblocks commands
    default: op
